version: "3.8"
services:
  backend:
    image: "egorkra/nineline:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev