server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nineline
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
