server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nineline
    username: root
    password: 3L]cnN/g]L%{n3?p~q
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-h1uk-ini.us.auth0.com/

auth0:
  audience: https://egor-dev.com
  clientSecret:

