name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  MYSQL_VERSION: 5.7
  MYSQL_DB: nineline
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_DB: ${{ env.MYSQL_DB }}
#          MYSQL_USER: ${{ env.MYSQL_USER }}
#          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
#          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
#        ports:
#          - 33306:3306
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DB }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend